# Generated by Django 5.2.1 on 2025-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='motos/')),
                ('marca', models.CharField(choices=[('HONDA', 'Honda'), ('AVELLOZ', 'Avelloz'), ('SHINERAY', 'Shineray'), ('YAMAHA', 'Yamaha')], default='HONDA', max_length=20)),
            ],
        ),
    ]
