# Generated by Django 5.2 on 2025-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='acessorios/')),
                ('tipo', models.CharField(choices=[('CAPACETE', 'Capacete'), ('LUVA', 'Luva'), ('BOTA', 'Bota'), ('JOELHEIRAS', 'Joelheira'), ('JAQUETA', 'Jaqueta')], default='CAPACETE', max_length=20)),
            ],
        ),
    ]
