# Generated by Django 5.2 on 2025-06-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_acessorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessorios', models.ManyToManyField(blank=True, to='loja.acessorio')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.moto')),
            ],
        ),
    ]
