# Generated by Django 5.2 on 2025-06-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_carrinho_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.moto'),
        ),
    ]
