# Generated by Django 5.2 on 2025-06-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_carrinho_acessorios_remove_carrinho_moto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinhoAcessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.acessorio')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_acessorio', to='loja.carrinho')),
            ],
        ),
    ]
